### PR TITLE
Upgrade to RKNPU2 1.6.0

### PR DESCRIPTION
**Pull request by marty1885**
Rockchip just released RKNPU2 1.6.0. They ditched their rknpu2 repo and have put in rknn-toolkit2. This PR adapts useful-transformers into working with RKNPU2.

### CODE REVIEW

**Comment by keveman** [comment]
Thanks a lot for the PR, @marty1885. I need a few days to verify on my end and I'll approve for you to merge.

**Comment by marty1885** [comment]
NP, have a nice holiday and new year!

**Comment by keveman** [comment]
Thanks a lot @marty1885. Please go ahead and merge it in.

**Review by keveman — APPROVED** [review]

**Comment by marty1885** [comment]
What do you mean? I don't have write access and merge is blocked by protections. Can you merge it?
image

**Comment by keveman** [comment]
Done. I'll fix the permissions for future PRs.

**Pull request merged**
